Missing dependency
Add the dependency on colorama to Linux-readme.txt.

WIthout this library installed, I get:

python2 start.py
Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from colorama import init, Fore, Back, Style
ImportError: No module named colorama